### ISSUE TITLE
RunYAPO.exe closes unexpectedly

### ISSUE THREAD

**Issue by ghost** [cooperdk/YAPO-e-plus#2]
When running RunYAPO.exe, a modal displays stating the location of the static and media files, then shuts down. No GUI launches.
![Yapo E+](https://user-images.githubusercontent.com/16834360/74227056-fa4b7300-4cbd-11ea-8ec8-bb6f083ce974.png)

**Comment by cooperdk** [comment]
The software doesn't open a browser. You manually use the app by browsing to http://127.0.0.1:8000/

How did you install Python and the required software?

**Comment by cooperdk** [comment]
Please, let me know if you still have this issue?

**Comment by the0perator18** [comment]
I have it, error looks like this: 


```
____    ____  ___       ______     ______         _______
\   \  /   / /   \     |   _  \   /  __  \       |   ____|   _
 \   \/   / /  ^  \    |  |_)  | |  |  |  |      |  |__    _| |_
  \_    _/ /  /_\  \   |   ___/  |  |  |  |      |   __|  |_   _|
    |  |  /  _____  \  |  |      |  `--'  |      |  |____   |_|
    |__| /__/     \__\ | _|       \______/       |_______|

    For changes to the main branch, please consult the guide.
=================================================================

Static files dir is: H:\YAPO\videos\static
Media files dir is: H:\YAPO\videos\media
Performing system checks...

Exception ignored in thread started by: <function check_errors.<locals>.wrapper at 0x000001ECDF3063A0>
Traceback (most recent call last):
  File "H:\YAPO\env\lib\site-packages\django\utils\autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "H:\YAPO\env\lib\site-packages\django\core\management\commands\runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "H:\YAPO\env\lib\site-packages\django\core\management\base.py", line 356, in check
    all_issues = self._run_checks(
  File "H:\YAPO\env\lib\site-packages\django\core\management\base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "H:\YAPO\env\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "H:\YAPO\env\lib\site-packages\django\core\checks\urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "H:\YAPO\env\lib\site-packages\django\core\checks\urls.py", line 26, in check_resolver
  File "H:\YAPO\env\lib\site-packages\django\urls\resolvers.py", line 256, in check
  File "H:\YAPO\env\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "H:\YAPO\env\lib\site-packages\django\urls\resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "H:\YAPO\env\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "H:\YAPO\env\lib\site-packages\django\urls\resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\philm\scoop\apps\python\current\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "H:\YAPO\YAPO\urls.py", line 20, in <module>
    from videos import views
  File "H:\YAPO\videos\views.py", line 10, in <module>
    import videos.addScenes
  File "H:\YAPO\videos\addScenes.py", line 5, in <module>
    from videos import filename_parser
  File "H:\YAPO\videos\filename_parser.py", line 8, in <module>
    from videos.scrapers import filenames
ImportError: cannot import name 'filenames' from 'videos.scrapers' (unknown location)
(env) YAPO master *% $ ^C
```

**Comment by cooperdk** [comment]
the0perator18,
your error happens due to my mistake. It does work in my install, but maybe the environment option breaks it.

To fix, change line 8 in videos/filename_parser.py to:

`import videos.scrapers.filenames`

This will be changed in the next commit.

**Comment by cooperdk** [comment]
For the original author of this bug report:

Your YAPO installation is in C:\Program Files (x86)\YAPO.

As mentioned in the README, currently, YAPO must be installed in a drive root, fx D:\YAPO.
